### ISSUE TITLE
Some movie/anime page are crashing!!

### ISSUE THREAD

**Issue by VAJRESH** [VAJRESH/media-tracker#15]
When I am logging into my account, I notice that One piece tv series page is getting crashed

![WhatsApp Image 2023-10-09 at 23 48 54_7c5f8b74](https://github.com/VAJRESH/media-tracker/assets/64434374/ca047ef5-3178-41f3-ad2a-9ece9fc89103)

Page URI: https://media-tracker.onrender.com/tv/37854

**Comment by pra3886** [comment]
hey...its a bug i guess..let me fix it...

**Comment by VAJRESH** [comment]
thanks for closing this issue
